### PR TITLE
Maven Release

### PR DESCRIPTION
**Pull request by Lmmb74**
I added maven support in order to get builds easier :)
A jenkins server should be created to get development builds automatically :D

### CODE REVIEW

**Comment by Lmmb74** [comment]
*bump

**Comment by samerton** [comment]
Thanks for this, I'll check it out shortly.

**Comment by Lmmb74** [comment]
Have you checked it?

**Comment by samerton** [comment]
Just having some issues resolving the dependencies (not used Maven for a project before), sorry it's taking a bit longer than it should :P

**Comment by Lmmb74** [comment]
No trouble :)

**Comment by samerton** [comment]
@Lmmb74 If you wouldn't mind, I'd appreciate it :)
I've imported the project as a Maven project into Eclipse, however I'm getting missing artefacts for bungeecord.jar and spigot.jar.

**Comment by Lmmb74** [comment]
I am importing the project in Eclipse right now to check the problem.

**Comment by Lmmb74** [comment]
Seems strange, I had no trouble importing.

**Comment by samerton** [comment]
@Lmmb74 Are you using the File -> Import -> Maven -> Existing Maven Projects method of importing? I've tried a couple of times, and I'm still getting the missing artifact errors for both `com.namelessmc:bungeecord:jar:1.0-SNAPSHOT` and `com.namelessmc:spigot:jar:1.0-SNAPSHOT`.

**Comment by Lmmb74** [comment]
Yes. You are just importing the main one (the modular one <pom packaging>), right?

**Comment by Lmmb74** [comment]
That will allow the dependencies to be located in the parent repositories.

**Comment by samerton** [comment]
I'm importing everything within the `Nameless-Plugin-master` folder

**Comment by Lmmb74** [comment]
Then I'm out of ideas because I am not getting any trouble. Would you mind making a maven debug inside Eclipse and a maven clean install execution where you cloned the repo?

**Comment by samerton** [comment]
The error within the Maven debug is [this](http://pastebin.com/raw/khE5uPe6).

Unfortunately I can't try a clean install as I don't have Maven installed outside Eclipse on this machine at the moment.

**Comment by Lmmb74** [comment]
OOOOOOOOOOOOOOOOOOOOOOOOWWWWWWWWWWWWWWWWWWWWWWWWwwwwwwwwwwwwwwww. It's trying to get the dependencies from the repositories provided in the parent pom when it only has to resolve them from the other modules and shade them. I had this trouble before when I was making the maven project. I do not usually use Eclipse for maven :P

**Comment by Lmmb74** [comment]
Gimme a minute and I will tell you how to solve it ;)

**Comment by Lmmb74** [comment]
Fixed

**Comment by Lmmb74** [comment]
Btw, changed typo cause I prefer tab-spacing format rather than 4-space format :).

**Comment by samerton** [comment]
Thanks, works perfectly! ;)

**Comment by Lmmb74** [comment]
:D

**Pull request merged**
